import { Job } from './types';

export const seedJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    team: 'Engineering',
    location: 'San Francisco, CA',
    shortDescription: 'Build beautiful, performant interfaces for our core product.',
    fullDescription: `We're looking for a Senior Frontend Engineer to join our Engineering team. You'll work closely with design and product to build pixel-perfect, accessible interfaces that delight our users.\n\n**Responsibilities:**\n- Architect and implement complex UI features using React and TypeScript\n- Collaborate with designers to translate Figma specs into production code\n- Mentor junior engineers and conduct code reviews\n- Drive frontend best practices across the organization\n\n**Requirements:**\n- 5+ years of experience with React and TypeScript\n- Strong understanding of web performance optimization\n- Experience with design systems and component libraries\n- Excellent communication skills`,
    status: 'public',
    postedAt: '2026-03-10T00:00:00Z',
  },
  {
    id: '2',
    title: 'Product Designer',
    team: 'Design',
    location: 'Remote (US)',
    shortDescription: 'Shape the future of our product experience.',
    fullDescription: `Join our Design team to create intuitive, beautiful experiences that make complex workflows feel simple.\n\n**Responsibilities:**\n- Own the end-to-end design process from research to final implementation\n- Create wireframes, prototypes, and high-fidelity designs in Figma\n- Conduct user research and usability testing\n- Maintain and evolve our design system\n\n**Requirements:**\n- 4+ years of product design experience\n- Strong portfolio demonstrating UX problem-solving\n- Proficiency with Figma and prototyping tools\n- Experience working in agile, cross-functional teams`,
    status: 'public',
    postedAt: '2026-03-08T00:00:00Z',
  },
  {
    id: '3',
    title: 'Backend Engineer',
    team: 'Engineering',
    location: 'New York, NY',
    shortDescription: 'Design and build scalable APIs and data infrastructure.',
    fullDescription: `We need a Backend Engineer to help scale our infrastructure and build reliable, performant APIs.\n\n**Responsibilities:**\n- Design and implement RESTful and GraphQL APIs\n- Optimize database queries and data models\n- Build monitoring and alerting systems\n- Participate in on-call rotations\n\n**Requirements:**\n- 3+ years of backend development experience\n- Proficiency with Node.js and TypeScript\n- Experience with PostgreSQL or similar relational databases\n- Understanding of distributed systems concepts`,
    status: 'public',
    postedAt: '2026-03-05T00:00:00Z',
  },
  {
    id: '4',
    title: 'Internal Tools Developer',
    team: 'Engineering',
    location: 'San Francisco, CA',
    shortDescription: 'Build internal tooling to improve team productivity.',
    fullDescription: 'This is a draft job posting that should not appear publicly.',
    status: 'draft',
    postedAt: '2026-03-01T00:00:00Z',
  },
  {
    id: '5',
    title: 'Head of Marketing',
    team: 'Marketing',
    location: 'Remote (Global)',
    shortDescription: 'Lead our marketing strategy and brand positioning.',
    fullDescription: `We're hiring a Head of Marketing to drive our go-to-market strategy and build a world-class marketing team.\n\n**Responsibilities:**\n- Define and execute the overall marketing strategy\n- Build and manage a high-performing marketing team\n- Drive brand awareness and lead generation\n- Measure and optimize marketing ROI\n\n**Requirements:**\n- 8+ years in B2B SaaS marketing\n- Proven track record of scaling marketing teams\n- Strong analytical and strategic thinking skills\n- Excellent written and verbal communication`,
    status: 'public',
    postedAt: '2026-03-12T00:00:00Z',
  },
];
